<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-12T17:29:33 IST" name="Default suite" finished-at="2021-10-12T17:29:55 IST" duration-ms="21347">
    <groups>
    </groups>
    <test started-at="2021-10-12T17:29:33 IST" name="Default test" finished-at="2021-10-12T17:29:55 IST" duration-ms="21347">
      <class name="com.vitiger.testScriptWithTestmethod.tc_06">
        <test-method is-config="true" signature="createconnnectionWithDatabase()[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:33 IST" name="createconnnectionWithDatabase" finished-at="2021-10-12T17:29:33 IST" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createconnnectionWithDatabase -->
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:33 IST" name="launchBrowser" finished-at="2021-10-12T17:29:37 IST" duration-ms="3528" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="OpenApp()[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:37 IST" name="OpenApp" finished-at="2021-10-12T17:29:44 IST" duration-ms="7580" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method signature="loginFailedTest()[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:44 IST" name="loginFailedTest" finished-at="2021-10-12T17:29:44 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [b] but found [a]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [b] but found [a]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vitiger.testScriptWithTestmethod.tc_06.loginFailedTest(tc_06.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFailedTest -->
        <test-method is-config="true" signature="logOut(org.testng.ITestResult)[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:45 IST" name="logOut" finished-at="2021-10-12T17:29:55 IST" duration-ms="9791" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginFailedTest status=FAILURE method=tc_06.loginFailedTest()[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:55 IST" name="closeBrowser" finished-at="2021-10-12T17:29:55 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeDB()[pri:0, instance:com.vitiger.testScriptWithTestmethod.tc_06@333291e3]" started-at="2021-10-12T17:29:55 IST" name="closeDB" finished-at="2021-10-12T17:29:55 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDB -->
      </class> <!-- com.vitiger.testScriptWithTestmethod.tc_06 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
